/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as TakeIndexRouteImport } from './routes/take.index'
import { Route as AuthenticatedExamsNewRouteImport } from './routes/_authenticated/exams.new'
import { Route as AuthenticatedExamsIdIndexRouteImport } from './routes/_authenticated/exams.$id.index'
import { Route as AuthenticatedExamsIdGradeRouteImport } from './routes/_authenticated/exams.$id.grade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TakeIndexRoute = TakeIndexRouteImport.update({
  id: '/take/',
  path: '/take/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExamsNewRoute = AuthenticatedExamsNewRouteImport.update({
  id: '/exams/new',
  path: '/exams/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsIdIndexRoute =
  AuthenticatedExamsIdIndexRouteImport.update({
    id: '/exams/$id/',
    path: '/exams/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsIdGradeRoute =
  AuthenticatedExamsIdGradeRouteImport.update({
    id: '/exams/$id/grade',
    path: '/exams/$id/grade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/results': typeof AuthenticatedResultsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/take/': typeof TakeIndexRoute
  '/exams/new': typeof AuthenticatedExamsNewRoute
  '/exams/$id/grade': typeof AuthenticatedExamsIdGradeRoute
  '/exams/$id/': typeof AuthenticatedExamsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/results': typeof AuthenticatedResultsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/take': typeof TakeIndexRoute
  '/exams/new': typeof AuthenticatedExamsNewRoute
  '/exams/$id/grade': typeof AuthenticatedExamsIdGradeRoute
  '/exams/$id': typeof AuthenticatedExamsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/take/': typeof TakeIndexRoute
  '/_authenticated/exams/new': typeof AuthenticatedExamsNewRoute
  '/_authenticated/exams/$id/grade': typeof AuthenticatedExamsIdGradeRoute
  '/_authenticated/exams/$id/': typeof AuthenticatedExamsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/results'
    | '/sources'
    | '/take/'
    | '/exams/new'
    | '/exams/$id/grade'
    | '/exams/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/results'
    | '/sources'
    | '/take'
    | '/exams/new'
    | '/exams/$id/grade'
    | '/exams/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/results'
    | '/_authenticated/sources'
    | '/take/'
    | '/_authenticated/exams/new'
    | '/_authenticated/exams/$id/grade'
    | '/_authenticated/exams/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TakeIndexRoute: typeof TakeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/take/': {
      id: '/take/'
      path: '/take'
      fullPath: '/take/'
      preLoaderRoute: typeof TakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/exams/new': {
      id: '/_authenticated/exams/new'
      path: '/exams/new'
      fullPath: '/exams/new'
      preLoaderRoute: typeof AuthenticatedExamsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$id/': {
      id: '/_authenticated/exams/$id/'
      path: '/exams/$id'
      fullPath: '/exams/$id/'
      preLoaderRoute: typeof AuthenticatedExamsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$id/grade': {
      id: '/_authenticated/exams/$id/grade'
      path: '/exams/$id/grade'
      fullPath: '/exams/$id/grade'
      preLoaderRoute: typeof AuthenticatedExamsIdGradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedExamsNewRoute: typeof AuthenticatedExamsNewRoute
  AuthenticatedExamsIdGradeRoute: typeof AuthenticatedExamsIdGradeRoute
  AuthenticatedExamsIdIndexRoute: typeof AuthenticatedExamsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedExamsNewRoute: AuthenticatedExamsNewRoute,
  AuthenticatedExamsIdGradeRoute: AuthenticatedExamsIdGradeRoute,
  AuthenticatedExamsIdIndexRoute: AuthenticatedExamsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TakeIndexRoute: TakeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
